core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="admindashboard"),
    path('clientes', views.clientes, name="clientes"),
    path('clientes/delete/<int:cliente_id>', views.eliminarCliente, name="eliminar_cliente"),
    
    path('formula/imc', views.imc, name="imc"),
    path('formula/pesocorregido', views.pesoCorregido, name="pesocorregido"),
    path('formula/ger', views.ger, name="ger"),

    path('formula/lista-imc', views.lista_imc, name="lista_imc"),
    path('formula/lista-imc/delete/<int:imc_id>', views.eliminarCalculoIMC, name="eliminar_calculo_imc"),
    path('formula/lista-pesocorregido', views.lista_pesocorregido, name="lista_pesocorregido"),
    path('formula/lista-pesocorregido/delete/<int:pesocorregido_id>', views.eliminarCalculoPesoCorregido, name="eliminar_calculo_pesocorregido"),
    path('formula/lista-ger', views.lista_ger, name="lista_ger"),
    path('formula/lista-ger/delete/<int:ger_id>', views.eliminarCalculoGer, name="eliminar_calculo_ger"),
    path('formula/lista-dieta', views.lista_dieta, name="lista_dieta"),
    path('formula/lista-dieta/delete/<int:dieta_id>', views.eliminarCalculoDieta, name="eliminar_calculo_dieta"),
    path('formula/lista-dieta/edit/<int:dieta_id>', views.editarCalculoDieta, name="editar_calculo_dieta"),

    path('formula/grupos-nutri', views.gruposNutricionales, name="grupos-nutri"),
    path('formula/lista-grupos-nutri', views.lista_gruposNutricionales, name="lista_grupo_nutricional"),
    path('formula/lista-grupos-nutri/delete/<int:grupo_id>', views.eliminarCalculoGrupoNutri, name="eliminar_calculo_grupo"),
    path('formula/menu', views.menu, name="menu"),
    path('formula/dieta', views.dieta, name="dieta"),
    path('api/client/<int:client_id>', views.get_client_info, name="get_client_info"),


    path('calendario/', views.calendario, name="calendario"),
    path('historial-calendario/', views.historial_calendario, name="historial-calendario"),
    path('historial-calendario/delete/<int:cita_id>', views.eliminarCita, name="eliminar_cita"),
    path('api/appointment/<int:cita_id>', views.get_info_cita, name="get_info_cita"),
]

nutrisalud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from web.urls import web_patterns

urlpatterns = [

    #paths core
    path('', include('core.urls')),
    
    #paths web
    path('', include(web_patterns)),

    #paths contact
    path('contact/', include('contact.urls')),
    
    #paths citas
    path('citas/', include('citas.urls')),

    #paths accounts
    path('accounts/', include('registration.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    

    #paths admin
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

web/urls.py
from django.urls import path, re_path
from . import views

web_patterns = ([
    path('web/', views.home, name="home"),
    path('web/#about', views.home, name="about"),
    path('web/#services', views.home, name="services"),
    path('web/#contact', views.home, name="contact"),
], 'web')

core/models.py
from django.db import models
from django.contrib.auth.models import User
from registration.models import Profile

# Create your models here.

class IMC(models.Model):

    client = models.ForeignKey(Profile, on_delete = models.CASCADE, related_name='imc')
    imc = models.FloatField(verbose_name = "IMC", default=0)
    weight_level = models.CharField(max_length=30, verbose_name = "Nivel de Peso")
    created = models.DateTimeField(auto_now_add=True, verbose_name = "Fecha de Calculo")

    class Meta:
        ordering = ['-created']

class PesoCorregido(models.Model):

    client = models.ForeignKey(Profile, on_delete = models.CASCADE, related_name='pesocorregido')
    corrected_weight = models.FloatField(verbose_name = "Peso Corregido", default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name = "Fecha de Calculo")

    class Meta:
        ordering = ['-created']


class GER(models.Model):

    client = models.ForeignKey(Profile, on_delete = models.CASCADE, related_name='ger')
    ger = models.FloatField(verbose_name = "Requerimiento Energético en Reposo", default=0)
    get = models.FloatField(verbose_name = "Requerimiento Energético Total", default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name = "Fecha de Calculo")

    class Meta:
        ordering = ['-created']

class Food_Group(models.Model):

    food_group = models.CharField(max_length=255, verbose_name = "Grupo de Alimentos")
    food = models.CharField(max_length=255, verbose_name = "Alimento")
    amount = models.FloatField(default=0 , verbose_name = "Cantidad")
    unit = models.CharField(max_length=255, verbose_name = "Unidad")
    created = models.DateTimeField(auto_now_add=True, verbose_name = "Fecha de Agregado")
    
    def get_amount(self):
        return "{:.3g} {}".format(self.amount, self.unit) 

    class Meta:
        ordering = ['-created']

class Dieta(models.Model):

    client = models.ForeignKey(Profile, on_delete = models.CASCADE, related_name='dieta')
    vegetables = models.PositiveSmallIntegerField(verbose_name = "Verduras")
    fruits = models.PositiveSmallIntegerField(verbose_name = "Frutas")
    skim_milk = models.PositiveSmallIntegerField(verbose_name = "Leche descremada")
    low_fat_milk = models.PositiveSmallIntegerField(verbose_name = "Leche semidescremada")
    cereals_and_tubers_s = models.PositiveSmallIntegerField(verbose_name = "Cereales y Tuberculos (s/g)")
    cereals_and_tubers_c = models.PositiveSmallIntegerField(verbose_name = "Cereales y Tuberculos (c/g)")
    legumes = models.PositiveSmallIntegerField(verbose_name = "Leguminosas")
    whole_milk = models.PositiveSmallIntegerField(verbose_name = "Leche entera")
    sugars_s = models.PositiveSmallIntegerField(verbose_name = "Azucares s/g")
    sugars_c = models.PositiveSmallIntegerField(verbose_name = "Azucares c/g")
    protein_mbg = models.PositiveSmallIntegerField(verbose_name = "Proteinas AOA mbg")
    protein_bg = models.PositiveSmallIntegerField(verbose_name = "Proteinas AOA bg")
    oils_and_fats_s = models.PositiveSmallIntegerField(verbose_name = "Aceites y grasas s/p")
    oils_and_fats_c = models.PositiveSmallIntegerField(verbose_name = "Aceites y grasas c/p")
    protein_mg = models.PositiveSmallIntegerField(verbose_name = "Proteinas AOA mg")
    protein_ag = models.PositiveSmallIntegerField(verbose_name = "Proteinas AOA ag")

    kcal_carbohidratos = models.FloatField(default=0 , verbose_name = "Kcal Carbohidratos")
    kcal_proteinas = models.FloatField(default=0 , verbose_name = "Kcal Proteinas")
    kcal_lipidos = models.FloatField(default=0 , verbose_name = "Kcal Lipidos")
    distribucion_carbohidratos = models.FloatField(default=0 , verbose_name = "Distribucion Carbohidratos")
    distribucion_proteinas = models.FloatField(default=0 , verbose_name = "Distribucion Proteinas")
    distribucion_lipidos = models.FloatField(default=0 , verbose_name = "Distribucion Lipidos")
    kcal_total = models.FloatField(default=0 , verbose_name = "Kcal TOTAL")

    created = models.DateTimeField(auto_now_add=True, verbose_name = "Fecha de Agregado")

    class Meta:
        ordering = ['-created']

core/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User

class IMCForm(forms.ModelForm):
    client = forms.ModelChoiceField(queryset=Profile.objects.filter(user__groups__name='cliente'), label='Cliente', widget=forms.Select(attrs={
        'class': 'form-control select2'
    }))
    weight = forms.FloatField(label = "Peso (kg)", required=True, widget=forms.NumberInput(
        attrs={'class':'form-control'}))
    height = forms.FloatField(label = "Estatura (m)", required=True, widget=forms.NumberInput(
        attrs={'class':'form-control'}))

    class Meta:
        model = IMC
        fields = ["client"]

    def save(self, commit=True):
        imc = super(IMCForm, self).save(commit=False)

        imc.imc = self.cleaned_data.get('weight') / (self.cleaned_data.get('height') * self.cleaned_data.get('height'))

        if imc.imc < 18.5:
            imc.weight_level = "Bajo Peso"
        elif imc.imc < 25:
            imc.weight_level = "Normal"
        elif imc.imc < 29.9:
            imc.weight_level = "Sobrepeso"
        else:
            imc.weight_level = "Obeso"
        if commit:
            imc.save()

        return imc

class PesoCorregidoForm(forms.ModelForm):

    client = forms.ModelChoiceField(queryset=Profile.objects.filter(user__groups__name='cliente'), label='Cliente', widget=forms.Select(attrs={
        'class': 'form-control select2'
    }))
    height = forms.FloatField(label = "Estatura (m)", required=True, widget=forms.NumberInput(
        attrs={'class':'form-control'}))
    gender = forms.CharField(label = "Genero", required=True,widget=forms.Select(attrs={
        'class': 'custom-select mr-sm-2'
    }))

    class Meta:
        model = PesoCorregido
        fields = ["client"]

    def save(self, commit=True):
        pesocorregido = super(PesoCorregidoForm, self).save(commit=False)

        if self.cleaned_data.get('gender') == "1":
            pesocorregido.corrected_weight = 23 * (self.cleaned_data.get('height') * self.cleaned_data.get('height'))
        elif self.cleaned_data.get('gender') == "2":
            pesocorregido.corrected_weight = 21.5 * (self.cleaned_data.get('height') * self.cleaned_data.get('height'))

        if commit:
            pesocorregido.save()

        return pesocorregido

    
class GERForm(forms.ModelForm):

    client = forms.ModelChoiceField(queryset=Profile.objects.filter(user__groups__name='cliente'), label='Cliente', widget=forms.Select(attrs={
        'class': 'form-control select2'
    }))
    weight = forms.FloatField(label = "Peso (kg)", required=True, widget=forms.NumberInput(
        attrs={'class':'form-control'}))
    size = forms.FloatField(label = "Talla (cm)", required=True, widget=forms.NumberInput(
        attrs={'class':'form-control'}))
    age = forms.FloatField(label = "Edad (años)", required=True, widget=forms.NumberInput(
        attrs={'class':'form-control'}))
    gender = forms.CharField(label = "Genero", required=True,widget=forms.Select(attrs={
        'class': 'custom-select mr-sm-2'
    }))
    lifestyle = forms.CharField(label = "Estilo de Vida", required=True,widget=forms.Select(attrs={
        'class': 'custom-select mr-sm-2'
    }))

    class Meta:
        model = GER
        fields = ["client"]

    def save(self, commit=True):
        ger = super(GERForm, self).save(commit=False)

        if self.cleaned_data.get('gender') == "1":
            ger.ger = (9.99 * self.cleaned_data.get('weight')) + (6.25 * self.cleaned_data.get('size')) - (4.92 * self.cleaned_data.get('age')) + 5
        elif self.cleaned_data.get('gender') == "2":
            ger.ger = (9.99 * self.cleaned_data.get('weight')) + (6.25 * self.cleaned_data.get('size')) - (4.92 * self.cleaned_data.get('age')) - 161

        if self.cleaned_data.get('lifestyle') == "1":
            ger.get = ger.ger * 1.545
        elif self.cleaned_data.get('lifestyle') == "2":
            ger.get = ger.ger * 1.845
        elif self.cleaned_data.get('lifestyle') == "3":
            ger.get = ger.ger * 2.2

        if commit:
            ger.save()

        return ger

class Food_GroupForm(forms.ModelForm):

    class Meta:
        model = Food_Group
        fields = ["food_group", "food", "amount", "unit"]

class DietForm(forms.ModelForm):
    client = forms.ModelChoiceField(queryset=Profile.objects.filter(user__groups__name='cliente'), label='Cliente', widget=forms.Select(attrs={
        'class': 'form-control select2'
    }))
    
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            if field == 'client':
                continue
            self.fields[field].widget.attrs['class'] = 'form-control'
            
            self.fields[field].initial = 0

    class Meta:
        model = Dieta
        exclude = ["created"]


core/templates/core/formulas/ger.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}GER{% endblock %}

{% block links %}
  <link href="{% static '/lib/select2-4.0.13/css/select2.css' %}" rel="stylesheet"/>
  <link href="{% static '/lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
  <script src="{% static '/lib/select2-4.0.13/js/select2.js' %}"></script>
{% endblock %}

{% block content %}
<strong>Calculo del requerimiento energético en reposo</strong>
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-8 mx-auto mb-5">
        <form action="" method="post">{% csrf_token %}
          <h3 class="mb-4">GER y GET</h3>
          {{ form.errors }}
          <p>
            <label>Cliente:</label>
            {{ form.client }}
          </p>
          <p>
            <label>Genero:</label>
            <select class="form-control mr-sm-2" name="gender" id="id_gender">
              <option selected>Elegir...</option>
              <option value="1">Masculino</option>
              <option value="2">Femenino</option>
            </select>
          </p>          
          <p>
            <label>Estilo de Vida:</label>
            <select class="form-control mr-sm-2" name="lifestyle" id="id_lifestyle">
              <option selected>Elegir...</option>
              <option value="1">Sedentario</option>
              <option value="2">Activo</option>
              <option value="3">Vigoroso</option>
            </select>
          </p>
          <p>
            <label>Peso (kg):</label>
            <input type="number" name="weight" id="id_weight" class="form-control" step="0.01" min="0">
          </p>
          <p>
            <label>Estatura (cm):</label>
            <input type="number" name="size" id="id_size" class="form-control" step="0.01" min="0">
          </p>
          <p>
            <label>Edad (años):</label>
            <input type="number" name="age" id="id_age" class="form-control" min="0">
          </p>
          <div class="row">
            <div class="col-md-6">
              <p class="text-center">
                <label class="control-label h3">GER:</label>
              </p>
              <p class="text-center h1">
                  <label id="id_ger"></label>
              </p>
            </div>
            <div class="col-md-6">
              <p class="text-center">
                <label class="control-label h3">GET:</label>
              </p>
              <p class="text-center h1">
                  <label id="id_get"></label>
              </p>
            </div>
          </div>
          <p><input type="submit" class="btn btn-primary btn-block" value="Asignar"></p>
        </form>
      </div>
    </div>
  </div>
</main>
<script>
  $(document).ready(function () {
    $('.select2').select2({
      theme:'bootstrap4'
    });
  });

  $(function(){
		$("input").change(function(){
			var peso = Number($("#id_weight").val());
			var estatura = Number($("#id_size").val());
			var edad = Number($("#id_age").val());
			var genero = document.getElementById("id_gender").value;
			var estilovida = document.getElementById("id_lifestyle").value;
			
      var ger = 0
      var get = 0 
      if (genero){
        if (genero==='1'){
          ger = (9.99 * peso) + (6.25 * estatura) - (4.92 * edad) + 5
          $("#id_ger").text((ger).toFixed(2));
        } else if (genero==='2'){
          ger = (9.99 * peso) + (6.25 * estatura) - (4.92 * edad) - 161
          $("#id_ger").text((ger).toFixed(2));
        }
      }else{
        $("#id_ger").text(0);
      }

      if (estilovida){
        if (estilovida==='1'){
          get = ger * 1.545
          $("#id_get").text((get).toFixed(2));
        } else if (estilovida==='2'){
          get = ger * 1.845
          $("#id_get").text((get).toFixed(2));
        } else if (estilovida==='3'){
          get = ger * 2.2
          $("#id_get").text((get).toFixed(2));
        }
      }else{
        $("#id_get").text(0);
      }
		});
	});
</script>
{% endblock %}

core/templates/core/formulas/gruposnutricionales.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Grupos Nutricionales{% endblock %}

{% block content %}
<strong>Grupos Nutricionales</strong>
<main role="main">
    <div class="container">
        <div class="row mt-3">
        <div class="col-md-8 mx-auto mb-5">
            <form action="" method="post">{% csrf_token %}
            <h3 class="mb-4">Grupos Nutricionales</h3>
            {{ form.errors }}
            <p>
                <label>Grupo de alimentos:</label>
                <select name="food_group" id="food_group" class="form-control mr-sm-2">
                <option selected>Elegir...</option>
                <option value="Verdura">Verdura</option>
                <option value="Frutas">Frutas</option>
                <option value="Cereal y tubérculos">Cereal y tubérculos</option>
                <option value="Leguminosas">Leguminosas</option>
                <option value="Alimentos origen animal">Alimentos origen animal</option>
                <option value="Leche">Leche</option>
                <option value="Aceite y grasas">Aceite y grasas</option>
                <option value="Azúcares">Azúcares</option>
                <option value="Alimentos libres de energía">Alimentos libres de energía</option>
                <option value="Bebidas alcohólicas">Bebidas alcohólicas</option>
                </select>
            </p>
            <p>
                <label>Alimento:</label>
                <input type="text" name="food" id="id_food" class="form-control" id="placeholder" placeholder="Manzana">
            </p>
            <p>
                <label>Cantidad:</label>
                <input type="number" name="amount" id="id_amount" class="form-control" step="0.01" min="0">
            </p>
            <p>
                <label>Unidad:</label>
                <select name="unit" id="id_unit" class="form-control mr-sm-2">
                <option selected>Elegir...</option>
                <option value="kg">kg</option>
                <option value="gr">gr</option>
                <option value="1 pz">1 pz</option>
                <option value="½ pz">½ pz</option>
                <option value="1/4pz">1/3 pz</option>
                <option value="1/4pz">1/4 pz</option>
                <option value="1 tz">1 tz</option>
                <option value="1/2tz">1/2 tz</option>
                <option value="1/8 tz">1/3 tz</option>
                <option value="1/8 tz">1/4 tz</option>
                <option value="1/8 tz">1/8 tz</option>
                <option value="1 cda">1 cda</option>
                <option value="½ cda">½ cda</option>
                <option value="1/3 cda">1/3 cda</option>
                <option value="1/4 cda">1/4 cda</option>
                <option value="1 cdita">1 cdita</option>
                <option value="½ cdita">½ cdita</option>
                <option value="1/3 cdit">1/3 cdita</option>
                <option value="1/4 cdita">1/4 cdita</option>
                </select>
            </p>
            <p><input type="submit" class="btn btn-primary btn-block" value="Agregar"></p>
            </form>
        </div>
        </div>
    </div>
</main>
{% endblock %}

core/templates/core/formulas/imc.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}IMC{% endblock %}

{% block links %}
  <link href="{% static '/lib/select2-4.0.13/css/select2.css' %}" rel="stylesheet"/>
  <link href="{% static '/lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
  <script src="{% static '/lib/select2-4.0.13/js/select2.js' %}"></script>
{% endblock %}

{% block content %}
<strong>Calculo de indice de masa corporal</strong>
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-8 mx-auto mb-5">
        <form action="" method="post">{% csrf_token %}
          <h3 class="mb-4">IMC</h3>
          {{ form.errors }}
          <p>
            <label>Cliente:</label>
            {{ form.client }}
          </p>
          <p>
            <label>Peso (kg):</label>
            <input type="number" name="weight" id="id_weight" class="form-control" step="0.01" min="0">
          </p>
          <p>
            <label>Estatura (m):</label>
            <input type="number" name="height" id="id_height" class="form-control" step="0.01" min="0">
          </p>
          <p class="text-center">
            <label class="control-label h3">IMC:</label>
          </p>
          <p class="text-center h1">
            <label id="id_imc"></label>
          </p>
          <p><input type="submit" class="btn btn-primary btn-block" value="Asignar"></p>
        </form>
      </div>
    </div>
  </div>
</main>
<script>
  $(document).ready(function () {
    $('.select2').select2({
      theme:'bootstrap4'
    });
  });

  $(function(){
		$("input").change(function(){
			var peso = Number($("#id_weight").val());
			var altura = Number($("#id_height").val());
			if (altura){
				$("#id_imc").text((peso/(altura*altura)).toFixed(2));
			}else{
        $("#id_imc").text(0);
      }
		});
	});
</script>

{% endblock %}

core/templates/core/formulas/pesocorregido.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Peso Corregido{% endblock %}

{% block links %}
  <link href="{% static '/lib/select2-4.0.13/css/select2.css' %}" rel="stylesheet"/>
  <link href="{% static '/lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
  <script src="{% static '/lib/select2-4.0.13/js/select2.js' %}"></script>
{% endblock %}

{% block content %}
<strong>Calculo del Peso Corregido</strong>
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-8 mx-auto mb-5">
        <form action="" method="post">{% csrf_token %}
          <h3 class="mb-4">Peso Corregido</h3>
          {{ form.errors }}
          <p>
            <label>Cliente:</label>
            {{ form.client }}
          </p>
          <p>
            <label>Genero:</label>
            <select name="gender" id="id_gender" class="form-control mr-sm-2">
              <option selected>Elegir...</option>
              <option value="1">Masculino</option>
              <option value="2">Femenino</option>
            </select>
          </p>
          <p>
            <label>Estatura (m):</label>
            <input type="number" name="height" id="id_height" class="form-control" step="0.01" min="0">
          </p>
          <p class="text-center">
            <label class="control-label h3">Peso Corregido:</label>
          </p>
          <p class="text-center h1">
              <label id="id_peso_corregido"></label>
          </p>
          <p><input type="submit" class="btn btn-primary btn-block" value="Asignar"></p>
        </form>
      </div>
    </div>
  </div>
</main>
<script>
  $(document).ready(function () {
    $('.select2').select2({
      theme:'bootstrap4'
    });
  });

  $(function(){
		$("input").change(function(){
			var altura = Number($("#id_height").val());
			var genero = document.getElementById("id_gender").value;
			if (genero){
        if (genero==='1'){
          $("#id_peso_corregido").text((23 * altura * altura).toFixed(2));
        } else if (genero==='2'){
          $("#id_peso_corregido").text((21.5 * altura * altura).toFixed(2));
        }
      }else{
        $("#id_peso_corregido").text(0);
      }
		});
	});

</script>
{% endblock %}