core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="admindashboard"),
    path('clientes', views.clientes, name="clientes"),
    path('clientes/delete/<int:cliente_id>', views.eliminarCliente, name="eliminar_cliente"),
    
    path('formula/imc', views.imc, name="imc"),
    path('formula/pesocorregido', views.pesoCorregido, name="pesocorregido"),
    path('formula/ger', views.ger, name="ger"),

    path('formula/lista-imc', views.lista_imc, name="lista_imc"),
    path('formula/lista-imc/delete/<int:imc_id>', views.eliminarCalculoIMC, name="eliminar_calculo_imc"),
    path('formula/lista-pesocorregido', views.lista_pesocorregido, name="lista_pesocorregido"),
    path('formula/lista-pesocorregido/delete/<int:pesocorregido_id>', views.eliminarCalculoPesoCorregido, name="eliminar_calculo_pesocorregido"),
    path('formula/lista-ger', views.lista_ger, name="lista_ger"),
    path('formula/lista-ger/delete/<int:ger_id>', views.eliminarCalculoGer, name="eliminar_calculo_ger"),
    path('formula/lista-dieta', views.lista_dieta, name="lista_dieta"),
    path('formula/lista-dieta/delete/<int:dieta_id>', views.eliminarCalculoDieta, name="eliminar_calculo_dieta"),
    path('formula/lista-dieta/edit/<int:dieta_id>', views.editarCalculoDieta, name="editar_calculo_dieta"),

    path('formula/grupos-nutri', views.gruposNutricionales, name="grupos-nutri"),
    path('formula/lista-grupos-nutri', views.lista_gruposNutricionales, name="lista_grupo_nutricional"),
    path('formula/lista-grupos-nutri/delete/<int:grupo_id>', views.eliminarCalculoGrupoNutri, name="eliminar_calculo_grupo"),
    path('formula/menu', views.menu, name="menu"),
    path('formula/dieta', views.dieta, name="dieta"),
    path('api/client/<int:client_id>', views.get_client_info, name="get_client_info"),


    path('calendario/', views.calendario, name="calendario"),
    path('historial-calendario/', views.historial_calendario, name="historial-calendario"),
    path('historial-calendario/delete/<int:cita_id>', views.eliminarCita, name="eliminar_cita"),
    path('api/appointment/<int:cita_id>', views.get_info_cita, name="get_info_cita"),
]

nutrisalud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from web.urls import web_patterns

urlpatterns = [

    #paths core
    path('', include('core.urls')),
    
    #paths web
    path('', include(web_patterns)),

    #paths contact
    path('contact/', include('contact.urls')),
    
    #paths citas
    path('citas/', include('citas.urls')),

    #paths accounts
    path('accounts/', include('registration.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    

    #paths admin
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

web/urls.py
from django.urls import path, re_path
from . import views

web_patterns = ([
    path('web/', views.home, name="home"),
    path('web/#about', views.home, name="about"),
    path('web/#services', views.home, name="services"),
    path('web/#contact', views.home, name="contact"),
], 'web')

citas/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta, datetime

# Create your models here.

class Appointment(models.Model):
    client = models.ForeignKey(User, on_delete = models.CASCADE, related_name='cita')
    date = models.DateField(null=True, blank=True, verbose_name="Fecha de cita")
    hour = models.TimeField(null=True, blank=True, verbose_name="Hora de la cita")
    commentary = models.TextField(max_length=150, null = True, blank= True, verbose_name="Comentario de Cita")

    def endhour(self):
        return datetime.combine(self.date, self.hour) + timedelta(hours=1)

    def datewithhour(self):
        return datetime.combine(self.date ,self.hour)

    class Meta:
        ordering = ['-date']

citas/forms.py
from django import forms
from .models import Appointment
from registration.models import Profile
from django.contrib.auth.models import User


class AppointmentForm(forms.ModelForm):
    phone = forms.CharField(label='Telefono:', max_length=10)

    class Meta:
        model = Appointment
        fields = ["date", "hour", "commentary"]

    def save(self, commit=True, request = None):
        appointment = super(AppointmentForm, self).save(commit=False)

        appointment.client = request.user
        
        if commit:
            request.user.profile.phone = self.cleaned_data['phone']
            request.user.profile.save()
            appointment.save()

        return appointment

    

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label = "Nombre", required=True, widget=forms.TextInput(
        attrs={'name':'name' ,'class':'form-control', 'id':'name', 'placeholder':'Tú nombre', 'data-rule':'minlen:4', 'data-msg':'Please enter at least 4 chars'}
    ), min_length=3, max_length=100)
    email = forms.EmailField(label = "Email", widget=forms.EmailInput(
        attrs={'class':'form-control', 'name':'email', 'id':'email', 'placeholder':'Tú correo', 'data-rule':'email', 'data-msg':'Please enter a valid email'}
    ), min_length=3, max_length=100)
    subject = forms.CharField(label = "Asunto", required=True, widget=forms.TextInput(
        attrs={'name':'subject' ,'class':'form-control', 'id':'subject', 'placeholder':'Asunto', 'data-rule':'minlen:4', 'data-msg':'Please enter at least 8 chars of subject'}
    ), min_length=3, max_length=100)
    content = forms.CharField(label = "Contenido", required=True, widget=forms.Textarea(
        attrs={'class':'form-control', 'name':'message', 'rows':5, 'data-rule':'required', 'data-msg':'Please write something for us', 'placeholder':'Mensaje'}
    ), min_length=10, max_length=1000)


nutrisalud/accounts/forms.py
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ValidationError

from django import forms
from .models import Profile
from django.contrib.auth.models import User


# Create your forms here.

class LoginForm(forms.Form):
    email = forms.CharField(label='Correo electrónico:', max_length=100)
    password = forms.CharField(label='Contraseña:', max_length=100)

class SignupForm(forms.ModelForm):
    last_name_m = forms.CharField(label='Apellido Materno:', max_length=100)
    password = forms.CharField(label='Contraseña:', max_length=100)
    password2 = forms.CharField(label='Repetir Contraseña:', max_length=100)

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]

        labels = {
            'first_name': 'Nombre(s):',
            'last_name': 'Apellido Paterno:',
            'email': 'Correo electrónico:',
        }

    def clean(self):
        data = super(SignupForm, self).clean()
        if not ('first_name' in data and data['first_name']):
            raise ValidationError("Se requiere nombre")

        if 'password' in data and data['password'] != data['password2']:
            raise ValidationError("Contraseñas no coinciden")

    def save(self, commit=True):
        user = super(SignupForm, self).save(commit=False)
        profile = {
            "last_name_m": self.cleaned_data.get('last_name_m')

        }
        user.profile = Profile(**profile)

        if not user.id:
            user.password = make_password(self.cleaned_data['password'])
            user.username = user.email
        if commit:
            user.save()
            user.profile.save()

        return user

    

    

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from registration.decorators import unauthenticated_user, allow_users, admin_only
from django.http import JsonResponse,HttpResponseRedirect
from django.shortcuts import get_object_or_404

from django.contrib.auth.models import User

from .models import IMC, PesoCorregido, GER, Food_Group, Dieta
from .forms import IMCForm, PesoCorregidoForm, GERForm, Food_GroupForm, DietForm
from citas.models import *
from registration.models import *
from django.contrib import messages


# Create your views here.

@login_required(login_url='login')
@admin_only
def home(request):
    return render(request, 'core/index-dashboard.html')

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def clientes(request):  
    clientes = User.objects.filter(groups__name='cliente')
    context = {'clientes':clientes}
    return render(request, 'core/clientes.html', context)

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def eliminarCliente(request, cliente_id):
    cliente = User.objects.get(id=cliente_id)
    cliente.delete()
    messages.success(request, "Eliminado Correctamente")
    return redirect('clientes')

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def imc(request):
    context = {}
    form = IMCForm()
    if request.method == 'POST':
        form = IMCForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_imc')
    context = {'form':form}
    return render(request, 'core/formulas/imc.html', context)

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def eliminarCalculoIMC(request, imc_id):
    imc = IMC.objects.get(id=imc_id)
    imc.delete()
    messages.success(request, "Eliminado Correctamente")
    return redirect('lista_imc')

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def pesoCorregido(request):
    context = {}
    form = PesoCorregidoForm()
    if request.method == 'POST':
        form = PesoCorregidoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_pesocorregido')
    context = {'form':form}
    return render(request, 'core/formulas/pesocorregido.html', context)

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def ger(request):
    context = {}
    form = GERForm()
    if request.method == 'POST':
        form = GERForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_ger')
    context = {'form':form}
    return render(request, 'core/formulas/ger.html', context)


@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])    
def gruposNutricionales(request):
    context = {}
    form = Food_GroupForm()
    if request.method == 'POST':
        form = Food_GroupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_grupo_nutricional')
    context = {'form':form}
    return render(request, 'core/formulas/gruposnutricionales.html')

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def lista_gruposNutricionales(request):  
    lista_gruposNutricionales = Food_Group.objects.all()
    context = {'lista_gruposNutricionales':lista_gruposNutricionales}
    return render(request, 'core/lista_gruposNutricionales.html', context)

@login_required(login_url='login')
@admin_only
def menu(request):
    return render(request, 'core/menu.html')

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])    
def dieta(request):
    context = {}
    form = DietForm()
    if request.method == 'POST':
        form = DietForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_dieta')

    context = {'form':form, "action":"Agregar"}
    return render(request, 'core/formulas/dietas.html', context)

@login_required(login_url='login')
@allow_users(allowed_roles=['admin']) 
def get_client_info(request, client_id):
    client = get_object_or_404(Profile, id=client_id)
    data = {
        "imc": client.get_imc(),
        "peso": client.get_peso(),
        "ger": client.get_ger(),
        "get": client.get_get(),
    }
    return JsonResponse(data, status=200)

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def lista_dieta(request):  
    lista_dieta = Dieta.objects.all()
    context = {'lista_dieta':lista_dieta}
    return render(request, 'core/lista_dieta.html', context)

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def editarCalculoDieta(request, dieta_id):
    context = {}
    dieta = Dieta.objects.get(id=dieta_id)
    form = DietForm(instance=dieta)
    if request.method == 'POST':
        form = DietForm(request.POST, instance=dieta)
        if form.is_valid():
            form.save()
            messages.success(request, "Modificado Correctamente")
            return redirect('lista_dieta')
    context = {"form":form, "action":"Editar"}
    return render(request, 'core/formulas/dietas.html', context)

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def eliminarCalculoDieta(request, dieta_id):
    dieta = Dieta.objects.get(id=dieta_id)
    dieta.delete()
    messages.success(request, "Eliminado Correctamente")
    return redirect('lista_dieta')


@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def lista_imc(request):  
    lista_imc = IMC.objects.all()
    context = {'lista_imc':lista_imc}
    return render(request, 'core/lista_imc.html', context)

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def lista_pesocorregido(request):  
    lista_pesocorregido = PesoCorregido.objects.all()
    context = {'lista_pesocorregido':lista_pesocorregido}
    return render(request, 'core/lista_pesocorregido.html', context)

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def lista_ger(request):  
    lista_ger = GER.objects.all()
    context = {'lista_ger':lista_ger}
    return render(request, 'core/lista_ger.html', context)

@login_required(login_url='login')
@admin_only
def calendario(request):
    context = {}
    lista_citas = Appointment.objects.all()
    context = {'lista_citas':lista_citas}
    return render(request, 'core/calendario.html', context)

@login_required(login_url='login')
@admin_only
def historial_calendario(request):
    context = {}
    lista_citas = Appointment.objects.all()
    context = {'lista_citas':lista_citas}
    return render(request, 'core/historial_calendario.html', context)

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def eliminarCita(request, cita_id):
    cita = Appointment.objects.get(id=cita_id)
    cita.delete()
    messages.success(request, "Eliminado Correctamente")
    return redirect('historial-calendario')

@login_required(login_url='login')
@allow_users(allowed_roles=['admin']) 
def get_info_cita(request, cita_id):
    cita = get_object_or_404(Appointment, id=cita_id)
    data = {
        "first_name": cita.client.first_name,
        "last_name": cita.client.last_name,
        "last_name_m": cita.client.profile.last_name_m,
        "date": cita.date,
        "hour": cita.hour,
        "email": cita.client.email,
        "phone": cita.client.profile.phone,
        "commentary":cita.commentary,
    }
    return JsonResponse(data, status=200)

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def eliminarCalculoPesoCorregido(request, pesocorregido_id):
    corrected_weight = PesoCorregido.objects.get(id=pesocorregido_id)
    corrected_weight.delete()
    messages.success(request, "Eliminado Correctamente")
    return redirect('lista_pesocorregido')

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def eliminarCalculoGer(request, ger_id):
    ger = GER.objects.get(id=ger_id)
    ger.delete()
    messages.success(request, "Eliminado Correctamente")
    return redirect('lista_ger')

@login_required(login_url='login')
@allow_users(allowed_roles=['admin'])
def eliminarCalculoGrupoNutri(request, grupo_id):
    grupo = Food_Group.objects.get(id=grupo_id)
    grupo.delete()
    messages.success(request, "Eliminado Correctamente")
    return redirect('lista_grupo_nutricional')

core/templates/core/calendario.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Calendario{% endblock %}
{% block links %}
<link href="{% static 'core/assets/extra-libs/datatables.net-bs4/css/dataTables.bootstrap4.css' %}" rel="stylesheet">
<!-- Custom CSS -->
<link href="{% static 'core/assets/libs/fullcalendar/dist/fullcalendar.min.css' %}" rel="stylesheet" />
<!-- Custom CSS -->
<link href="{% static 'core/dist/css/style.min.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-11">
            <div class="card">
                <div class="">
                    <div class="row">
                        <div class="col-lg-9">
                            <div class="card-body b-l calender-sidebar">
                                <div id="calendar"></div>
                            </div>
                        </div>
                    </div>
                </div>  
            </div>
        </div>
    </div>
</div>    
{% endblock %}
{% block js %}
    <script src="{% static 'core/assets/extra-libs/sparkline/sparkline.js' %}"></script>
    <script src="{% static 'core/assets/extra-libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'core/dist/js/pages/datatable/datatable-basic.init.js' %}"></script>

    <script src="{% static 'core/assets/libs/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'core/assets/extra-libs/taskboard/js/jquery.ui.touch-punch-improved.js' %}"></script>
    <script src="{% static 'core/assets/extra-libs/taskboard/js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'core/assets/libs/popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'core/assets/libs/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- apps -->
    <script src="{% static 'core/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js' %}"></script>

    <!--This page JavaScript -->
    <script src="{% static 'core/assets/libs/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'core/assets/libs/fullcalendar/dist/fullcalendar.min.js' %}"></script>
    <script src="{% static 'core/dist/js/pages/calendar/cal-init.js' %}"></script>
    <script>
        //initializing CalendarApp
        $(window).on('load', function() {
            var dates = [{% for cita in lista_citas %}
                            {title:'{{ cita.client.first_name }} {{ cita.client.last_name }}',
                            start:new Date('{{ cita.date|date:'Y-m-d' }} {{ cita.hour|date:'H:i:s' }}'),
                            end:new Date('{{ cita.date|date:'Y-m-d' }} {{ cita.endhour|date:'H:i:s' }}'),
                            className: 'bg-info'},
                        {% endfor %}]
            $.CalendarApp.init(dates)
        });
    </script>
{% endblock %}

core/templates/core/clientes.html
{% extends 'core/base.html' %}
{% load static %}

{% block message %}
<script>
    function eliminarCliente(id){
        Swal.fire({
            "title":"¿Estás seguro?",
            "text": "Esta acción no se puede deshacer",
            "icon": "question",
            "showCancelButton":true,
            "cancelButtonText":"No, Cancelar",
            "confirmButtonText":"Si, Eliminar",
            "confirmButtonColor":"#ff4f70"
        })
        .then(function(result) {
            if(result.isConfirmed) {
                window.location.href = "/clientes/delete/"+id
            }
        });
    }
</script>
{% endblock %}

{% block title %}Clientes{% endblock %}
{% block links %}<link href="{% static 'core/assets/extra-libs/datatables.net-bs4/css/dataTables.bootstrap4.css' %}" rel="stylesheet">{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Lista de clientes</h4>
                    <div class="table-responsive">
                        <table id="zero_config" class="table table-striped table-bordered no-wrap">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Apellido</th>
                                    <th>Correo</th>
                                    <th>Celular</th>
                                    <th>Accion</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cliente in clientes %}
                                <tr>
                                    <td>{{ cliente.first_name }}</td>
                                    <td>{{ cliente.last_name }}</td>
                                    <td>{{ cliente.email }}</td>
                                    <td>{{ cliente.profile.phone }}</td>
                                    <td>
                                        <!--<a class="btn btn-warning" href="{% url 'eliminar_cliente' cliente.id %}"><i class="fa fa-check"></i></a>-->
                                        <a class="btn btn-danger" href="#" onclick="eliminarCliente({{ cliente.id }})"><i class="fa fa-trash"></i></a>
                                        
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Apellido</th>
                                    <th>Correo</th>
                                    <th>Celular</th>
                                    <th>Accion</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block js %}
    <script src="{% static 'core/assets/extra-libs/sparkline/sparkline.js' %}"></script>
    <script src="{% static 'core/assets/extra-libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'core/dist/js/pages/datatable/datatable-basic.init.js' %}"></script>
{% endblock %}

core/templates/core/historial_calendario.html
{% extends 'core/base.html' %}
{% load static %}

{% block message %}
<script>
    function eliminarCita(id){
        Swal.fire({
            "title":"¿Estás seguro?",
            "text": "Esta acción no se puede deshacer",
            "icon": "question",
            "showCancelButton":true,
            "cancelButtonText":"No, Cancelar",
            "confirmButtonText":"Si, Eliminar",
            "confirmButtonColor":"#ff4f70"
        })
        .then(function(result) {
            if(result.isConfirmed) {
                window.location.href = "/historial-calendario/delete/"+id
            }
        });
    }
</script>
{% endblock %}

{% block title %}Citas{% endblock %}
{% block links %}<link href="{% static 'core/assets/extra-libs/datatables.net-bs4/css/dataTables.bootstrap4.css' %}" rel="stylesheet">{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Historial de Calendario</h4>
                    <div class="table-responsive">
                        <table id="zero_config" class="table table-striped table-bordered no-wrap">
                            <thead>
                                <tr>
                                    <th>Fecha de la Cita</th>
                                    <th>Nombre cliente</th>
                                    <th>Correo</th>
                                    <th>Telefono</th>
                                    <th>Accion</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cita in lista_citas %}
                                <tr>
                                    <td>{{ cita.date }}, {{ cita.hour }}</td>
                                    <td>{{ cita.client.profile }}</td>
                                    <td>{{ cita.client.email }}</td>
                                    <td>{{ cita.client.profile.phone }}</td>
                                    <td>
                                        <a class="btn btn-danger" href="#" onclick="eliminarCita({{ cita.id }})"><i class="fa fa-trash"></i></a>
                                        <a class="btn btn-primary" href="#" onclick="detailCita({{ cita.id }})"><i class="fa fa-eye"></i></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Fecha de la Cita</th>
                                    <th>Nombre cliente</th>
                                    <th>Correo</th>
                                    <th>Telefono</th>
                                    <th>Accion</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block js %}
    <script src="{% static 'core/assets/extra-libs/sparkline/sparkline.js' %}"></script>
    <script src="{% static 'core/assets/extra-libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'core/dist/js/pages/datatable/datatable-basic.init.js' %}"></script>

     

    <div class="modal fade" id="myModalCita" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cita</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>
                    <label>Nombre(s):</label>
                    <input type="text" name="first_name" required
                        id="id_first_name" class="form-control" readonly/>
                </p>
                <div class="row">
                <div class="col-lg-6">
                    <div class="grid-container">
                    <p>
                        <label>Apellido Paterno:</label>
                        <input type="text" name="last_name" required
                        id="id_last_name" class="form-control"  readonly/>
                    </p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="grid-container">
                    <p>
                        <label>Apellido Materno:</label>
                        <input type="text" name="last_name_m"
                        id="id_last_name_m" class="form-control" readonly/>
                    </p>
                    </div>
                </div>
                </div>
                <p>
                <label>Correo electronico:</label>
                <input type="email" name="email" required id="id_email" class="form-control" readonly>
                </p>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="grid-container">
                            <p>
                            <label>Telefono:</label>
                            <input type="text" name="phone" readonly
                                id="id_phone" class="form-control"/>
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="grid-container">
                            <p>
                            <label>Fecha:</label>
                            <input type="text" name="date" readonly
                                id="id_date" class="form-control"/>
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="grid-container">
                            <p>
                            <label>Hora:</label>
                            <input type="text" name="hour" readonly
                                id="id_hour" class="form-control"/>
                            </p>
                            </p>
                        </div>
                    </div>
                </div>
                <p>
                <label>Comentario:</label>
                <textarea name="commentary" id="id_commentary"class="form-control" rows="3" readonly ></textarea>
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Listo!</button>
            </div>
            </div>
        </div>
    </div>

    <script>
        function detailCita(id){
            jQuery.ajax({
                dataType: "json",
                type : "GET",
                url: "/api/appointment/"+id,
                success: function(data){
                    const monthNames = ["Ene", "Feb", "Mar", "Apr", "May", "Jun",
                        "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
                    ];
                    
                    var d = new Date(data.date);
                    
                    var date = d.getDate() + 1;
                    var month = monthNames[d.getMonth()];
                    var year = d.getFullYear();
                        
                    var dateStr = month + "-" + date + "-" + year;

                    $("#id_first_name").val(data.first_name)

                    $("#id_last_name").val(data.last_name)

                    $("#id_last_name_m").val(data.last_name_m)

                    $("#id_email").val(data.email)

                    $("#id_phone").val(data.phone)
                    
                    $("#id_date").val(dateStr)

                    $("#id_hour").val(data.hour)

                    $("#id_commentary").val(data.commentary)

                }
            });
            $('#myModalCita').modal('show');
        }
    </script>

{% endblock %}

core/templates/core/index-dashboard.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<strong>Te damos la bienvenida a NutriSalud</strong>
{% endblock %}